### ISSUE TITLE
AFRAME.anime not working

### ISSUE THREAD

**Issue by e-g-b** [supermedium/superframe#208]
I can't seem to tap into anime using your instructions. I'm not getting any errors. Like your example I'm using A-Frame 0.8.2 and your aframe-animation-component.min.js. 

All I'm trying to do is is hide an a-entity with an id of "device-phone" in my custom script file.

I've also tried adding amine.js and calling my animations with `anime({...});` but nothing has worked. Is there something I'm not doing right?

```
<!-- my scripts in head -->
<script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
<script src="js/aframe-animation-component.min.js"></script>
```

```
<!-- my html -->
<a-entity id="device-iphone" position="2 1.15 -0.83">
    <a-image width="1" height="2" src="#iphone" rotation="0 -70 0"></a-image>
  </a-entity>
```

```
// my JS
var phoneEl = document.querySelector('#device-iphone');

phoneEl.addEventListener('click', function() {
    console.log('phone has been clicked');
    AFRAME.anime({
      targets: phoneEl,
      opacity: 0,
      duration: 5000,
    });
});
```

**Comment by ngokevin** [comment]
Not sure. Should just be `AFRAME.anime.`. Can also try `AFRAME.ANIME`...

**Comment by e-g-b** [comment]
I figured it out. I couldn’t target the ID, I had to set up props and target an object var. I could tap into some of the anime animation properties for easing and timing.

**Comment by zyadmardini** [comment]
can you please elaborate on how you solved the issue ?
