### ISSUE TITLE
THREE.VRControls is not a constructor

### ISSUE THREAD

**Issue by Hulkmaster** [supermedium/superframe#211]
Using last version of aframe and orbitcontrols from npm gives this error

`THREE.VRControls is not a constructor`

```
    "aframe": "^0.8.2",
    "aframe-orbit-controls-component": "^1.0.0",
```

**Comment by Hulkmaster** [comment]
Also i've found strange thing

in `html examples` url is
`https://unpkg.com/aframe-orbit-controls@1.2.0`

in npm it is `1.0.0`

Had 1.2.0 version been published to npm?

**Comment by Hulkmaster** [comment]
Okay, found an issue

on documentation page link is incorrect

https://github.com/supermedium/superframe/tree/master/components/orbit-controls/

`npm install aframe-orbit-controls-component`

should be

`npm install aframe-orbit-controls`

**Comment by Hulkmaster** [comment]
actually opened issue, documentation needs changes

**Comment by ngokevin** [comment]
fixed thanks!
