### ISSUE TITLE
[look-at] example doesn't work

### ISSUE THREAD

**Issue by janpio** [supermedium/superframe#213]
The `look-at` example is not working:
https://supermedium.com/superframe/components/look-at/
https://supermedium.com/superframe/components/look-at/examples/basic/
The gif is animated, but in reality nothing moves at all.

**Comment by janpio** [comment]
Downloading the sample code from https://github.com/supermedium/superframe/blob/master/components/look-at/examples/basic/index.html and replacing `build.js` with `https://cdn.jsdelivr.net/gh/supermedium/superframe/components/look-at/dist/aframe-look-at-component.js` fixes the problem.

**Comment by ngokevin** [comment]
Fixed example. Thanks!
