### ISSUE TITLE
[orbit-controls] Add change keybinding functionality

### ISSUE THREAD

**Issue by Skayle** [supermedium/superframe#218]
Hello,

I was wondering if it is possible to include the functionality of changing keybindings in the [orbit-controls] component?

As for mobile/touch there exists a standardized interaction pattern, but for desktop having both mouse buttons taken away by camera controls is simply not good for user interaction. The default orbit control behaviour for most games and 3D software is e.g. to use the middle mouse click for panning.

I am currently working on a web-based 3D configurator, which would need the left click for selection/interaction, the middle mouse click for panning, the middle mouse scroll for zooming and the right click for camera rotation. This proves to be difficult to implement with the current [orbit-controls] provided here.

Greetings from Germany,
Skayle

P.S. Please forgive me if I have overlooked a simple way of doing this, my experience level with aframe and threejs is quite low...

P.P.S. I just updated my aframe to 0.9.0 (awesome update!) which rendered the old orbit-control component I was using unusable, which is why I got here.

**Comment by ngokevin** [comment]
Hi, I suggest you fork and modify the controls to fit your customized needs. Thanks!
