### ISSUE TITLE
The Haptics with Aframe 0.9.0 on Vive Controller not working.

### ISSUE THREAD

**Issue by smeybi** [supermedium/superframe#219]
Hi
With Aframe 0.9.0 to force the haptics on the Vive Controller no longer work. Is there a way to access the haptics?

Thanks!

**Comment by ngokevin** [comment]
Thanks for the report, perhaps with the tracked-controls / WebXR changes, it might've broke the way the haptics component grabs the controllers in its `init` function. We'll get around to it later unless you want to check it out. Thanks!

**Comment by smeybi** [comment]
I examined the problem. It is a problem of firefox himself. In Supermedium works fine. With Firefox does not work either set pulse direct.
navigator.getGamepads()[0].hapticActuators[0].pulse( 1, 1000 )
Oculus Rift haptics works fine.
I ask firefox and give feedback.

**Comment by smeybi** [comment]
I have reported Firefox the issue. They have confirmed and fix it in version 68.

**Comment by ngokevin** [comment]
Thanks, always worked in Supermedium too
