### ISSUE TITLE
issue with [state] and bind-for v6.5.0

### ISSUE THREAD

**Issue by AntoineLucidWeb** [supermedium/superframe#225]
Hi,
I can't seem to make the bind-for work in the aframe state componant v6.5.0, even with the example on the simple shopping list in the doc... any idea why ?
Thanks !

**Comment by AntoineLucidWeb** [comment]
Ok, so with this really simple example which basicly come from the documentation :
`<html>

<head>
    <script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-state-component@6.5.0/dist/aframe-state-component.min.js"></script>
    <script>
        AFRAME.registerState({
            initialState: {

                shoppingList: [
                    { name: 'milk', amount: 2 },
                    { name: 'eggs', amount: 12 }
                ]
            }
        });
    </script>
</head>

<body>
    <a-scene>
        <a-entity bind-for="for: shoppingItem; in: shoppingList; key: name">
            <template>
                <a-entity bind__text="value: shoppingItem.name" data-amount="{{ shoppingItem.amount }}"></a-entity>
            </template>
        </a-entity>
    </a-scene>
</body>

</html>`

I get this ;
`TypeError: Cannot read property 'name' of undefined
    at Object.eval [as shoppingItem.name] (eval at s (aframe-state-component.min.js:1), <anonymous>:3:29)
    at Object.s [as select] (aframe-state-component.min.js:1)
    at i.onStateUpdate (aframe-state-component.min.js:1)
    at i.update (aframe-state-component.min.js:1)
    at initComponent (component.js:307)
    at i.updateProperties (component.js:279)
    at i.module.exports.Component (component.js:62)
    at new i (component.js:600)
    at HTMLElement.value (a-entity.js:326)
    at HTMLElement.value (a-entity.js:483)`

Apparently this lib tries to find the bind element inside the bind-for in the state, which it won't find because the values are in the shoppinglist array: 
`Failure loading node:   Error: [aframe-state-component] Key 'shoppingItem.name' not found in state. #null[bind__text]`

Unless I'm doing something wrong, it looks like there is nothing (anymore ?) to specify where the value should be looked for in case of bind-for in the lib

**Comment by AntoineLucidWeb** [comment]
still not working on v6.7.0 and aframe 0.9.2

**Comment by ngokevin** [comment]
Sorry, should be `{{ shoppingItem.name }}`. I will update.

If you do `updateInPlace: true`, you can do `bind_item__text="value: shoppingItem.name"`.

Some real-world examples:

https://github.com/supermedium/moonrider
https://glitch.com/~aframe-building-ui

**Comment by carllx** [comment]
> Sorry, should be `{{ shoppingItem.name }}`. I will update.
> 
> If you do `updateInPlace: true`, you can do `bind_item__text="value: shoppingItem.name"`.
> 
> Some real-world examples:
> 
> https://github.com/supermedium/moonrider
> https://glitch.com/~aframe-building-ui

still not working on v6.8.0 and aframe 1.0.4
