### ISSUE TITLE
State component and React

### ISSUE THREAD

**Issue by bknill** [supermedium/superframe#230]
I'm using aframe with the state component as part of a React app.  I know this isn't advised, and it hasn't been a problem before - however it's for an Admin system that loads the scene in certain places.  In the player it's a PureComponent that never re-renders so it's not really a problem. 

Everything is fine when the scene first loads, but when the scene loads again the state component has a meltdown, seems to have lost half it's values and I get loads of errors i.e.

```
Failure loading node:   TypeError: Cannot read property 'split' of undefined
    at split (aframe-state-component.js:348)
    at Object.parseKeysToWatch (aframe-state-component.js:296)

Cannot read property 'trim' of undefined
    at NewComponent.onStateUpdate (aframe-state-component.js:735)
    at NewSystem.<anonymous> (aframe-state-component.js:490)
    at HTMLElement.<anonymous> (aframe-state-component.js:582)
    at HTMLElement.<anonymous> (aframe-master.js:59451)
    at SafeSubscriber._next (handleScenes.js:94)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:305)

```

I've caught the error and it seems to come from the update function

```
   if (typeof data === 'string' && data !== undefined) {
      lib.parseKeysToWatch(this.keysToWatch, data);
    } else {
      for (key in data) {
        if(data[key])
          lib.parseKeysToWatch(this.keysToWatch, data[key]);
          else {
            console.log('error', data, key)
            //throw new Error('Key does not exist:' + data + 'key' + key)
          }
      }
    }
```
Where some of the state values are undefined - even tho I never send them undefined values. 

Also if I remove all of the updates this still happens. 

I throught I might be able to reinitialse the state with scene.emit('@@INIT') but that has no effect.

**Comment by bknill** [comment]
OK I've taken out page reloading and extracted the

**Comment by ngokevin** [comment]
What does it mean when you say a scene loads and the scene is loaded again?

**Comment by bknill** [comment]
It's basically showing the component (with aframe in it) then removing it, then loading it again elsewhere in the app via React.

**Comment by ngokevin** [comment]
A-Frame and maybe state component doesn't really clean up well being attached / removed, it's not really a use case we target (full VR experience). Maybe I-Frames are a good workaround for this? Would be the ultimate cleanup.

**Comment by bknill** [comment]
Yea OK I think I've managed to seperate it from the React Layer. I tried throwing it into the html template and got the same problem as this https://github.com/aframevr/aframe/issues/4038

I've now kept it as a React component but outside of the Router which doesn't seem to be attaching it that well. 

If that fails then I might try iframes thanks Kevin.

**Comment by ngokevin** [comment]
Oh yeah that would work too if you can just hide the aframe instead of detaching it

**Comment by bknill** [comment]
OK thanks that's great thanks for your help. Working perfectly.
