### ISSUE TITLE
Geometry merger, Colors are not working

### ISSUE THREAD

**Issue by shubhamkumar0** [supermedium/superframe#235]
Here is a part of the code:

<a-entity buffer-geometry-merger material="vertexColors: vertex" merged-hover-highlight >
<a-entity geometry="primitive:box; skipCache: true;  width:32.0;	height:1.0;	depth:40.0 "
	 id="ID_bdd240c8fe7174e6ac1cfdd5282de76eb7ad6815"
		   position="19.0 1.5 23.0"	   		   
		   shader="flat"
		   material="visible: false"
		   color="#969696"
		   flat-shading="true">
	</a-entity>
</a-entity>
It should be something like this : 
https://drive.google.com/open?id=1AoUCmQ-I0bQ-yIN9ulQxKhGP74VB_h-t

But is like this : https://drive.google.com/open?id=1v6KUWqMIEJiVfu0cCsvoeNZPnNVbHp4e

**Comment by ngokevin** [comment]
What material is applied? A merged geometry will share the same material. You need to use vertex colors or something if you want different colors on certain parts of the geometry.

**Comment by shubhamkumar0** [comment]
I am using material="vertexColors: vertex"

**Comment by shubhamkumar0** [comment]
https://pastebin.com/x3j82mqw Here is a snippet of the code

**Comment by ngokevin** [comment]
Did you set the vertex colors of each vertex?

**Comment by shubhamkumar0** [comment]
I tried replicating the example code and used vertex-colors-buffer="baseColor: red". However nothing changes.

**Comment by ngokevin** [comment]
Maybe need `buffer: true ` also

**Comment by ngokevin** [comment]
You included those components? Can you post on glitch.com?

**Comment by shubhamkumar0** [comment]
https://glitch.com/edit/#!/join/eb7f3be4-caa1-4493-a914-7e844646dd9b

**Comment by shubhamkumar0** [comment]
I cannot post all the files for security, however this is what I am trying to do.

**Comment by shubhamkumar0** [comment]
It was an issue with using along with light="defaultLightsEnabled: false" in a-scene. removing this solved it for me.
