### ISSUE TITLE
AABB-colider keeps hitting old position

### ISSUE THREAD

**Issue by herrKlein** [supermedium/superframe#265]
Problem: the AABB-colider retains old position when object is moved.

It manifest also in the official example. [https://supermedium.com/superframe/components/aabb-collider/examples/basic/](https://supermedium.com/superframe/components/aabb-collider/examples/basic/). It seems the aabb colider component only remembers the old position of the block and when it moves it still colides with the old entity. The gif demonstrates this.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6085660/82588458-1f902d00-9b9b-11ea-915f-d1d14e348042.gif)

**Comment by damned** [comment]
not sure if this applies but on the readme for aabb-collider it mentions adding:

data-aabb-collider-dynamic

attribute if the 'target' is moving, they're assumed to be static - does that help?

**Comment by jadegamesuk** [comment]
To update @herrKlein - you have to add data-aabb-collider-dynamic="true" to the green box in order to fix this issue. I had the same issue you did and this will 100% fix the issue.
Can probably close this open issue now.

**Comment by vincentfretin** [comment]
@dmarcos you can close this issue.

**Comment by dmarcos** [comment]
This should be fixed now. closing
