### ISSUE TITLE
Needs update for aframe v1.4.0

### ISSUE THREAD

**Issue by Dirk-27** [supermedium/superframe#317]
The orbit-controls can't be used with aframe 1.4.0 due to the change of the underlying THREE.js version.

Known changes:
* THREE.Quaternion.inverse() is renamed to THREE.Quaternion.invert().
* THREE.Math is renamed to THREE.MathUtils

See #311

Task: Update of the entire code is needed.

**Comment by kfarr** [comment]
in progress: https://github.com/supermedium/superframe/pull/325

**Comment by dmarcos** [comment]
Fixed by https://github.com/supermedium/superframe/pull/325
