### ISSUE TITLE
orbit-controls doesnt work correctly with a-camera primitive

### ISSUE THREAD

**Issue by Dealerpriest** [supermedium/superframe#331]
I discovered a very peculiar behaviour when using the camera primitive where the orbit control zooms in and moves around seemingly random when rotating with the mouse. I observed the following:
- setting autorotate to true and not interacting with the mouse works fine. The camera moves around the target as expected.
- "grabbing" the scene and rotating behaves in the weird fashion. If rotating to a weird orientation with the mouse the autorotation is also affected from then on.
- This only seems to happen when using the a-camera primitive and not a-entity with camera component.

When using entity with camera component:
![orbit-control-works](https://github.com/supermedium/superframe/assets/363913/c9788832-c0e6-423a-8a89-c29a49ee3a3a)

When using camera primitive:
![orbit-control-weird](https://github.com/supermedium/superframe/assets/363913/8057854c-7455-4f75-8fc2-584d54b03fc3)

### Environment:
A vue 3 project where the aframe scene is inside a .vue single file component.
aframe v.1.5.0
aframe-orbit-control v.1.3.1

**Comment by vincentfretin** [comment]
Can you please provide a [glitch](https://glitch.com/edit/#!/aframe) without vue that triggers the issue? It will be easier to look into it.

**Comment by Dealerpriest** [comment]
Seems like v.1.3.1 of orbit-controls on unpkg is blank?
https://unpkg.com/aframe-orbit-controls@1.3.1/dist/aframe-orbit-controls.min.js

And the not minified version is including a reference to orbit-control from a lib folder.

**Comment by Dealerpriest** [comment]
Can also be seen here directly in the repo: https://github.com/supermedium/superframe/tree/master/components/orbit-controls/dist

Seems that the files in the folder above are the ones distributed to unpkg.

**Comment by Dealerpriest** [comment]
For some reason this commit: cd4201e0bf4cb3819f9784c486e133adfb32e359 wiped the whole minified version. I have a feeling it is an unfortunate mistake.

**Comment by vincentfretin** [comment]
That's indeed a separate issue, I created PR #332 to fix it.

**Comment by vincentfretin** [comment]
@Dealerpriest You can now use the 1.3.2 release ` <script src="https://unpkg.com/aframe-orbit-controls@1.3.2/dist/aframe-orbit-controls.min.js"></script>`
When doing #332 I updated the README. The README was wrong, it was missing `look-controls="enabled: false"`
The look-controls component should be disabled when using orbit-controls, that conflicts with each other.
When you're using a-camera it implies wasd-controls and look-controls, so you need to add `look-controls="enabled: false"` as well. That's your issue here.

**Comment by vincentfretin** [comment]
Also you would need to disable `wasd-controls` with `wasd-controls="enabled:false"` if you're using `<a-camera>`.

**Comment by Dealerpriest** [comment]
Very enlightening! Thank you! I will close this issue👍
