### ISSUE TITLE
orbit-controls initialization position is inaccurate

### ISSUE THREAD

**Issue by Sincenir** [supermedium/superframe#335]
I need reset function, but the component itself doesn't provide it.
I copied the component code. add reset.  Below is the code I added.

```
{
  init() {
    ....
   document.addEventListener('resetcamera', this.reset.bind(this)) 
  },

  reset() {
    this.controls.reset()
  }
}
```

```
setInterval(() => {
  document.querySelector('#camera').emit('resetcamera');
}, 3000);
```

after resetting, the camera does not appear in the default position.

I tried to write my own code to reset.
```
this.default = {
	position: { ...this.data.initialPosition },
	rotation: [
		el.getObject3D('camera').rotation.x,
		el.getObject3D('camera').rotation.y,
		el.getObject3D('camera').rotation.z,
	],
};
...
this.el.getObject3D('camera').position.copy(this.default.position);
this.el.getObject3D('camera').rotation.set(...this.default.rotation);
```

It's the same problem.

**Comment by vincentfretin** [comment]
I have no issue with the default example and aframe-orbit-controls@1.3.2
Calling `document.querySelector('[orbit-controls]').components["orbit-controls"].controls.reset()` works correctly.
Your issue is probably in your project. Please provide a glitch if you want further help.
Be sure to use 1.3.2, previous versions didn't have this line:
https://github.com/supermedium/superframe/blob/ff681da6ae6d19877c46e812c5727398c6f36a51/components/orbit-controls/index.js#L68

**Comment by Sincenir** [comment]
> I have no issue with the default example and aframe-orbit-controls@1.3.2 Calling `document.querySelector('[orbit-controls]').components["orbit-controls"].controls.reset()` works correctly. Your issue is probably in your project. Please provide a glitch if you want further help. Be sure to use 1.3.2, previous versions didn't have this line:
> 
> https://github.com/supermedium/superframe/blob/ff681da6ae6d19877c46e812c5727398c6f36a51/components/orbit-controls/index.js#L68



I use it.
![image](https://github.com/supermedium/superframe/assets/41592290/9c2847fc-00d1-4964-856a-805bc156bf76)
![image](https://github.com/supermedium/superframe/assets/41592290/a780b62d-10d8-4538-937c-c499dc574645)
![image](https://github.com/supermedium/superframe/assets/41592290/eac9d3b9-2de8-47d1-b3f7-f88f18c1bbde)

The three pictures above are:
- Start perspective
- Moved perspective
- Reset perspective

My code:
```
setInterval(() => {
document
	.querySelector('[orbit-controls]')
	.components['orbit-controls'].controls.reset();
}, 3000);
```

I tried writing a simple demo and had this problem.
```
<head>
  <title>My A-Frame Scene</title>
  <script src="https://aframe.io/releases/1.5.0/aframe.min.js"></script>
  <script src="https://unpkg.com/aframe-environment-component@1.3.3/dist/aframe-environment-component.min.js"></script>
  <script src="https://unpkg.com/aframe-orbit-controls@1.3.2/dist/aframe-orbit-controls.min.js"></script>

  <script>
    setInterval(() => {
      document
        .querySelector("[orbit-controls]")
        .components["orbit-controls"].controls.reset();
    }, 3000);
  </script>
</head>

<body>
  <a-scene
    shadow="enabled: true;"
    physics
    cursor="rayOrigin: ''"
    embedded="{needEmbedded}"
    environment="preset: forest"
  >
    <a-box position="0 1 0" width="2" height="2" depth="2"></a-box>
    <a-camera
      id="camera"
      orbit-controls="autoRotate: false; target: 0 0 0; initialPosition:0 1 5; minDistance:5; maxDistance: 180; rotateSpeed: 0.5"
    />
  </a-scene>
</body>
```

**Comment by vincentfretin** [comment]
You're the second person that use the a-camera primitive and having issues. You need to disable look-controls and wasd-controls that is auto added by the a-camera primitive or just use a-entity with camera, see my comments on https://github.com/supermedium/superframe/issues/331#issuecomment-1817870809

**Comment by Sincenir** [comment]
Prefect, I have used a-entity in my projects before.

I solved the problem by addiong `look-controls=”enabled: false“` and `wasd-controls="enabled: false"` .

What is the reason ? Although I turned on wasd, but I didn't operate the keyboard. Can't we solve this problem by adding attributes to element in our orbit-controls?

This new code:
```
<a-entity
	id="camera"
	camera="fov: {fov}"
	look-controls="enabled: false"
	wasd-controls="enabled: false"
	orbit-controls="target: 0 0 0; minDistance: 2; maxDistance: 180; initialPosition: 0 0 -20; rotateSpeed: 0.5"></a-entity>

```

**Comment by Sincenir** [comment]
> The issue is that look-controls and wasd-controls is moving the entity object3D (THREE.Group instance), orbit-controls is moving the camera object that is a child of the entity object3D. look-controls and orbit-controls are registering both handlers for mouse movement.

My idea is whenther in the `orbit-controls` component, the init method can push `this.el.setAttr('look-controls', 'enabled: false')` in the next eventloop to solve this problem.

This avoids the need for additional configuiration every time we use it. There is a certain conflict between our orbital camera and look controls and `look-controls` and `wasd-controls` .

Of course this is just an idea, I'm not sure if it can be implemented , I will try it during non-working hours.



I tried it and found that I can solve the problem by adding setAttr to init. See code commit above.
