### ISSUE TITLE
[orbit-controls] Conflicts with TransformControls

### ISSUE THREAD

**Issue by khalidmaquilang** [supermedium/superframe#339]
How to deactivate orbit-controls when using the transform controls?

**Comment by khalidmaquilang** [comment]
okay I got it.. i just added an event listener
```
let transform_controls = new TransformControls(camera, scene.sceneEl.renderer.domElement)
    transform_controls.attach(elem)
    transform_controls.addEventListener( 'dragging-changed', function ( event ) {
        current_camera = document.getElementById('camera')
        if (event.value) {
            current_camera.pause()
            return
        }

        current_camera.play()
    } )
```

**Comment by khalidmaquilang** [comment]
another problem is that after I move the entity, the camera returns to its target coordinate.. it doesn't stay in the previous position

**Comment by vincentfretin** [comment]
This seems to be a problem specific to your project code. You'll probably have a better chance of finding a solution to your issue on [WebXR Discord](https://discord.gg/csUFkqcp) aframe channel if you provide a [glitch example](https://glitch.com/~aframe) of the issue.

**Comment by vincentfretin** [comment]
That's great you find a fix. Hard to tell if it's a good one or not without a full example of what you're doing and how you switch between the two controls. You can close the issue if this change looks good to you.
